version: "3"
services:
  rabbitmq:
    container_name: polybus-rabbit
    image: rabbitmq:3.8-management
    ports:
    - "127.0.0.1:5672:5672"
    - "127.0.0.1:15672:15672"
    hostname: rabbitmq
  redis:
    container_name: polybus-redis
    image: redis:6.0
    ports:
    - "127.0.0.1:6379:6379"
