name: Continuous Integration
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    services:
      rabbitmq:
        image: rabbitmq:3.8
        ports:
        - 5672:5672
      redis:
        image: redis:6.0
        ports:
        - 6379:6379
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Build
      run: dotnet build src/Polybus.sln
    - name: Execute tests
      run: dotnet test src/Polybus.sln
